### ISSUE TITLE
[leo_gateway] Reading a file through s3fs can fail

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#1094]
### Prerequisites
- s3fs: https://github.com/dask/s3fs

### The code to reproduce
```python
import s3fs
import pandas as pd
import pyarrow.parquet as pq


ACCESS_KEY = '05236'
SECRET_ACCESS_KEY ='802562235'


boto3_dict = {'endpoint_url':'http://localhost:8080'}
fs = s3fs.S3FileSystem(key= ACCESS_KEY, secret = SECRET_ACCESS_KEY,
                       client_kwargs=boto3_dict)

# Write (Multipart Upload)
data_list = [[i,i*2,i*i,i/4,i/2,i/8] for i in xrange(400000)]
df = pd.DataFrame(data_list,columns=['a','b','c','d','e','f'])

with fs.open('test/test.parquet','wb') as fin:
    df.to_parquet(fin)

# Read (GET with Range)
tbl = None
with fs.open('test/test.parquet') as fin:
    tbl = pq.read_table(fin)
```

### What happens
```bash
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    tbl = pq.read_table(fin)
  File "/usr/local/lib/python2.7/dist-packages/pyarrow/parquet.py", line 939, in read_table
    pf = ParquetFile(source, metadata=metadata)
  File "/usr/local/lib/python2.7/dist-packages/pyarrow/parquet.py", line 64, in __init__
    self.reader.open(source, metadata=metadata)
  File "_parquet.pyx", line 651, in pyarrow._parquet.ParquetReader.open
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Invalid parquet file. Corrupt footer.
```

### Consideration
- Error happens when the parquet file size >= around 11MB
- Error never happens when the parquet file size <= 10MB

That being said, there is something wrong when handling Range GET to a file which chunks >= 3.

**Comment by mocchira** [comment]
It turns out that s3fs can make a part request in a different size on each part as described below.

```tsv
[PUT]   test    test/test.parquet       1       5596007 2018-08-01 14:28:13.217763 +0900        1533101293217754 200     49
[PUT]   test    test/test.parquet       2       5246231 2018-08-01 14:28:13.378359 +0900        1533101293378348 200     34
[PUT]   test    test/test.parquet       3       553677  2018-08-01 14:28:13.400117 +0900        1533101293400082 200     7
```

(The fifth column denotes the size of a body LeoGateway receives.)

Since LeoGateway expect the part size to be same among all parts except the last one when calculating the position where to start to read, LeoGateway fails to respond to a GET with Range request (wrong data can be returned to a client)

## How to fix
### Fundamental Fix
LeoGateway has to forget the above assumption and be able to handle GET with Range requests in accordance with "a different part can have a different part size" 
However, AFAIK there are no S3 clients other than s3fs in which "a different part can have a different part size" so some temporary solution specific to s3fs might be sufficient.

### Temporary Fix
There is a init param "default_block_size" which allow library users to specify the threshold over which an object will be sent through multipart upload so setting a enough large value to the param make multipart uploads never happen.

```python
boto3_dict = {'endpoint_url':'http://localhost:8080'}
fs = s3fs.S3FileSystem(key= ACCESS_KEY, secret = SECRET_ACCESS_KEY,
                       default_block_size = 104857600,
                       client_kwargs=boto3_dict)
```

With the above fix, I can read/write parquet files which size are larger than 10MB without any errors.

**Comment by mocchira** [comment]
As the temporal fix works for our users, I'll close the issue. Please reopen if there are some users who want the fundamental fix.
