### ISSUE TITLE
List Multipart Uploads (S3-API) Support

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#145]
"This operation lists in-progress multipart uploads. An in-progress multipart upload is a multipart upload that has been initiated, using the Initiate Multipart Upload request, but has not yet been completed or aborted."
- references:
  - [Using the REST API for Multipart Upload](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRESTAPImpUpload.html)
  - [List Multipart Uploads](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListMPUpload.html)

**Comment by mocchira** [comment]
boto the s3 client for python have used this API to retrieve the all parts uploaded into LeoFS.

**Comment by yosukehara** [comment]
I've copy Wilson's comment as below:

#### Issue
`leo_gateway` does not respond to `List Multipart Uploads` which reports on-going multipart upload in the server
http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListMPUpload.html

#### Outcome
`boto` (S3 Client in Python) cannot complete multipart upload as it would check if the corresponding multipart upload exists in the server

##### Comment
Among the clients tested, it is the only one doing such check in multipart upload ...

##### Test & Traceback
Test with `leo-project/leofs_client_tests/boto/leo.py`
```
Traceback (most recent call last):
  File "leo.py", line 82, in <module>
    multi_part.complete_upload()
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 317, in complete_upload
    xml = self.to_xml()
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 156, in to_xml
    for part in self:
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 122, in part_lister
    for part in parts:
TypeError: 'NoneType' object is not iterable
```

**Comment by windkit** [comment]
To clarify, `boto` uses `List Parts` to find out parts being uploaded to server
http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListParts.html

I closed the duplicate entry and would continue the discussion here while I am working on the issue
