### ISSUE TITLE
ETag from S3 did not match computed MD5

### ISSUE THREAD

**Issue by osier** [leo-project/leofs#216]
Similarly,  the testing failed in the middle with error "ETag from S3 did not match computed MD5".
### Error

```
create object image_file2639
done
create object image_file2640
done
create object image_file2641
done
create object image_file2642
done
create object image_file2643
done
create object image_file2644
Traceback (most recent call last):
  File "s3.py", line 30, in <module>
    s3_object.set_contents_from_filename("initrd.img-3.13.0-24-generic")
  File "/usr/lib/python2.7/dist-packages/boto/s3/key.py", line 1306, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/usr/lib/python2.7/dist-packages/boto/s3/key.py", line 1237, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.7/dist-packages/boto/s3/key.py", line 722, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.7/dist-packages/boto/s3/key.py", line 905, in _send_file_internal
    query_args=query_args
  File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 547, in make_request
    retry_handler=retry_handler
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1017, in make_request
    retry_handler=retry_handler)
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 894, in _mexe
    request.body, request.headers)
  File "/usr/lib/python2.7/dist-packages/boto/s3/key.py", line 847, in sender
    if not self.should_retry(response, chunked_transfer):
  File "/usr/lib/python2.7/dist-packages/boto/s3/key.py", line 927, in should_retry
    'ETag from S3 did not match computed MD5')
boto.exception.S3DataError: BotoClientError: ETag from S3 did not match computed MD5
```
### Testing script

```
#!/usr/bin/python
# coding: utf8

from boto.s3.connection import S3Connection, OrdinaryCallingFormat
from boto.s3.bucket import Bucket
from boto.s3.key import Key

AWS_ACCESS_KEY = "XXXXXXXXXXXXXXXX"
AWS_SECRET_ACCESS_KEY = "YYYYYYYYYYYYYYYYYYYYY"

conn = S3Connection(AWS_ACCESS_KEY,
                    AWS_SECRET_ACCESS_KEY,
                    host = "osier.com",
                    port = 80,
                    calling_format = OrdinaryCallingFormat(),
                    is_secure = False)

for i in range(1, 100):
    print "create bucket tttt243" + str(i)
    # create bucket
    bucket = conn.create_bucket("tttt243" + str(i))
    print "OK"

    for j in range(0, 10000000):
        print "create object image_file" + str(j)
        # create object
        s3_object = bucket.new_key("image_file" + str(j))

        # write
        s3_object.set_contents_from_filename("openssl")
        print "done"
```

**Comment by windkit** [comment]
As stated in the official document about Multipart

`The entity tag may or may not be an MD5 digest of the object data. If the entity tag is not an MD5 digest of the object data, it will contain one or more nonhexadecimal characters and/or will consist of less than 32 or more than 32 hexadecimal digits.`

While LeoFS follows the way of Amazon S3 during `put` (aka. (Hashing of Part Hashes)-(Number of Parts)), it seems to only return (Hashing of Part Hashes) during `get`

Old version of s3cmd may not check for it and would still raise the warning. s3cmd 1.5.2 works fine as it omits the checksum verification when the `-` is in the ETag.
