### ISSUE TITLE
[leo_object_storage] unexpected 500 error when getting a zero size object not cached

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#390]
This issue was found by the below test case within s3-tests .

```shell
ubuntu@ip-10-126-25-246:~/dev/s3-tests$ S3TEST_CONF=leofs.conf ./virtualenv/bin/nosetests -a '!fails_on_leofs'
....................................................................................E..............S.................
.................
======================================================================
ERROR: s3tests.functional.test_s3.test_object_copy_zero_size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/dev/s3-tests/virtualenv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/dev/s3-tests/s3tests/functional/test_s3.py", line 4518, in test_object_copy_zero_size
    key.copy(bucket, 'bar321foo')
  File "/home/ubuntu/dev/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/key.py", line 500, in copy
    src_version_id=self.version_id)
  File "/home/ubuntu/dev/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 871, in copy_
key
    query_args=query_args)
  File "/home/ubuntu/dev/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in m
ake_request
    retry_handler=retry_handler
  File "/home/ubuntu/dev/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in mak
e_request
    retry_handler=retry_handler)
  File "/home/ubuntu/dev/s3-tests/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1028, in _me
xe
    raise BotoServerError(response.status, response.reason, body)
BotoServerError: BotoServerError: 500 Internal Server Error
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Ple
ase try again.</Message><Resource>leofs-6tuw0s0e502krj9e72wipn7-78/bar321foo</Resource><RequestId></RequestId></Error
>
```

This issue don't happen when the target object is cached on leo_gateway.
Since LeoFS haven't used the cache on leo_gateway when copying an object, 
this test case failed.

**Comment by mocchira** [comment]
also can be reproced by
```shell
$ curl -v -X PUT http://localhost:8080/test/empty
$ leofs-adm purge-cache test/empty
$ curl -v http://localhost:8080/test/empty
```
