### ISSUE TITLE
interfacing with boto fails with SignatureDoesNotMatch

### ISSUE THREAD

**Issue by faisyl** [leo-project/leofs#408]
Setup a standalone leofs server. Tried the boto example code against it using boto=2.38.0. Usng same credentials on s3cmd, works fine. But boto always dies with (debug enabled):
```
2015-07-28 18:25:08,390 boto [DEBUG]:Using access key provided by client.
2015-07-28 18:25:08,390 boto [DEBUG]:Using secret key provided by client.
2015-07-28 18:25:08,391 boto [DEBUG]:path=/storage/
2015-07-28 18:25:08,391 boto [DEBUG]:auth_path=/storage/
2015-07-28 18:25:08,391 boto [DEBUG]:Method: PUT
2015-07-28 18:25:08,391 boto [DEBUG]:Path: /storage/
2015-07-28 18:25:08,391 boto [DEBUG]:Data: 
2015-07-28 18:25:08,391 boto [DEBUG]:Headers: {}
2015-07-28 18:25:08,392 boto [DEBUG]:Host: 192.168.67.103:8080
2015-07-28 18:25:08,392 boto [DEBUG]:Port: 8080
2015-07-28 18:25:08,392 boto [DEBUG]:Params: {}
2015-07-28 18:25:08,392 boto [DEBUG]:establishing HTTP connection: kwargs={'port': 8080, 'timeout': 70}
2015-07-28 18:25:08,392 boto [DEBUG]:Token: None
2015-07-28 18:25:08,393 boto [DEBUG]:StringToSign:
PUT


Tue, 28 Jul 2015 12:55:08 GMT
/storage/
2015-07-28 18:25:08,393 boto [DEBUG]:Signature:
AWS ebbaefcccdc7dbfc43f1:KzME+LWC650YPS5dUDQBFdDyouo=
2015-07-28 18:25:08,393 boto [DEBUG]:Final headers: {'Date': 'Tue, 28 Jul 2015 12:55:08 GMT', 'Content-Length': '0', 'Authorization': u'AWS ebbaefcccdc7dbfc43f1:KzME+LWC650YPS5dUDQBFdDyouo=', 'User-Agent': 'Boto/2.38.0 Python/2.7.9 Darwin/14.4.0'}
2015-07-28 18:25:08,429 boto [DEBUG]:Response headers: [('date', 'Tue, 28 Jul 2015 12:55:07 GMT'), ('connection', 'keep-alive'), ('content-length', '304'), ('server', 'LeoFS')]
Traceback (most recent call last):
  File "test_leo.py", line 22, in <module>
    bucket = conn.create_bucket("storage")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto/s3/connection.py", line 621, in create_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your AWS secret access key and signing method.</Message><Resource>192.168.67.103/storage/</Resource><RequestId></RequestId></Error>
```

**Comment by mocchira** [comment]
@faisyl Unfortunately we coudn't reproduce this issue with boto 2.38.0, LeoFS 1.2.12/1.1.5.
As we will try to reproduce this issue, Please let us know the detail of your environment.

- What version of LeoFS are you using?
- What version of Erlang are you using?
- What operating system(`uname -a`) and processor architecture(`cat /proc/cpuinfo`) and memory(`cat /proc/meminfo`) are you using?
- Your test code

**Comment by faisyl** [comment]
LeoFS version is  1.2.12-1, installed with the official ubuntu 14.04 installer deb.
OS is stock ubuntu 14.04. 
uname -a:
```
Linux ubuntu 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
When I fire up remote_console I see
```
Erlang/OTP 17 [erts-6.4] [source] [64-bit halfword] [async-threads:10] [kernel-poll:false]
```
Processor:
```
ubuntu@ubuntu:~$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2099.998
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx lm constant_tsc nopl pni cx16 x2apic hypervisor lahf_lm
bogomips	: 4199.99
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:
```
Mem info:
```
MemTotal:        2049940 kB
MemFree:          209588 kB
Buffers:          112720 kB
Cached:           658632 kB
SwapCached:          124 kB
Active:          1251100 kB
Inactive:         476444 kB
Active(anon):     808740 kB
Inactive(anon):   147572 kB
Active(file):     442360 kB
Inactive(file):   328872 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       2094076 kB
SwapFree:        2093552 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:        956128 kB
Mapped:            27128 kB
Shmem:               120 kB
Slab:              73004 kB
SReclaimable:      59588 kB
SUnreclaim:        13416 kB
KernelStack:        4816 kB
PageTables:         7348 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3119044 kB
Committed_AS:    4301360 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       11504 kB
VmallocChunk:   34359717628 kB
HardwareCorrupted:     0 kB
AnonHugePages:    868352 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       38784 kB
DirectMap2M:     2058240 kB
```
My Test code:
Exact code. Copied and pasted into an editor.
http://leo-project.net/leofs/docs/s3api_client/s3_client_boto.html
Differences: 
1. Changed credentials (from added user)
2. Changed bucket name from leofs-bucket to storage (an existing bucket) when the code failed.

**Comment by faisyl** [comment]
I tried the exact same code from the same box running leofs and that worked. This might have more to do with my mac box and the python env there than leofs then. Not sure why it fails from boto on mac tho'. You can close this ticket. Sorry for the trouble.

**Comment by mocchira** [comment]
@faisyl Thank you for the detail.
To make sure, we will try to reproduce on the environment which is as similar with yours as possible.

 - boto 2.38.0 running on mac
 - LeoFS 1.2.12-1 running on ubuntu 14.04

**Comment by mocchira** [comment]
@faisyl Sorry for the late reply.

From your debug log,

>> <?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your AWS secret access key and signing method.</Message><Resource>192.168.67.103/storage/</Resource><RequestId></RequestId></Error>

`192.168.67.103/storage/` might be the cause if you didn't exec `leofs-adm add-endpoint 192.168.67.103`.

Since LeoFS need to know the expected endpoint beforehand for retrieving a bucket name from URL and the default endpoints only include "localhost" and "s3.amazonaws.com",
you can accees LeoFS with URLs like ttp://localhost:8080/bucket/path_to_file, ttp://bucket.s3.amazonaws.com/path_to_file and so on.

So please add `192.168.67.103` to the endpoint if it's not added.

**Comment by yosukehara** [comment]
According to no response, I've closed this.
