### ISSUE TITLE
Manager master crashing in pthread/ethr_event.c

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#843]
Completely at random times, manager node crashes, first time:
```
Sep 19 14:11:32 bodies-master leo_manager[3332]: pthread/ethr_event.c:164: Fatal error in wait__(): Invalid argument (22)
Sep 19 14:11:32 bodies-master systemd[1]: leofs-manager-master.service: main process exited, code=killed, status=6/ABRT
Sep 19 14:11:33 bodies-master epmd[401]: epmd: failed to listen on socket
Sep 19 14:11:33 bodies-master leo_manager[32756]: Node 'manager_0@bodies-master.selectel.cloud.lan' not responding to pings.
Sep 19 14:11:33 bodies-master systemd[1]: leofs-manager-master.service: control process exited, code=exited status=1
Sep 19 14:11:33 bodies-master systemd[1]: Unit leofs-manager-master.service entered failed state.
Sep 19 14:11:33 bodies-master systemd[1]: leofs-manager-master.service failed.
Sep 19 14:11:53 bodies-master systemd[1]: leofs-manager-master.service holdoff time over, scheduling restart.
Sep 19 14:11:53 bodies-master systemd[1]: Started LeoFS master management node.
Sep 19 14:11:53 bodies-master systemd[1]: Starting LeoFS master management node...
Sep 19 14:11:54 bodies-master epmd[590]: epmd: failed to listen on socket
Sep 19 14:11:54 bodies-master leo_manager[406]: Config path: /etc/leofs/leo_manager_0
Sep 19 14:11:54 bodies-master leo_manager[406]: Exec: /usr/local/leofs/current/leo_manager_0/erts-9.0/bin/erlexec -noinput -boot /usr/local/leofs/current/leo_manager_0/releases/1/leo_manager -mode embedded -config /etc/leofs/leo_manager_0/app.config -args_file /etc/leofs/leo_manager_0/vm.args -- console
Sep 19 14:11:54 bodies-master leo_manager[406]: Root: /usr/local/leofs/current/leo_manager_0
Sep 19 14:11:54 bodies-master epmd[694]: epmd: failed to listen on socket
```
Second time:
```
Sep 20 18:55:53 bodies-master leo_manager[406]: pthread/ethr_event.c:164: Fatal error in wait__(): Invalid argument (22)
Sep 20 18:55:53 bodies-master systemd[1]: leofs-manager-master.service: main process exited, code=killed, status=6/ABRT
Sep 20 18:55:56 bodies-master epmd[1776]: epmd: failed to listen on socket
Sep 20 18:55:56 bodies-master leo_manager[1666]: Node 'manager_0@bodies-master.selectel.cloud.lan' not responding to pings.
Sep 20 18:55:56 bodies-master systemd[1]: leofs-manager-master.service: control process exited, code=exited status=1
Sep 20 18:55:56 bodies-master systemd[1]: Unit leofs-manager-master.service entered failed state.
Sep 20 18:55:56 bodies-master systemd[1]: leofs-manager-master.service failed.
Sep 20 18:56:16 bodies-master systemd[1]: leofs-manager-master.service holdoff time over, scheduling restart.
Sep 20 18:56:17 bodies-master systemd[1]: Started LeoFS master management node.
Sep 20 18:56:17 bodies-master systemd[1]: Starting LeoFS master management node...
Sep 20 18:56:18 bodies-master leo_manager[1781]: Config path: /etc/leofs/leo_manager_0
Sep 20 18:56:18 bodies-master leo_manager[1781]: Exec: /usr/local/leofs/current/leo_manager_0/erts-9.0/bin/erlexec -noinput -boot /usr/local/leofs/current/leo_manager_0/releases/1/leo_manager -mode embedded -config /etc/leofs/leo_manager_0/app.config -args_file /etc/leofs/leo_manager_0/vm.args -- console
Sep 20 18:56:18 bodies-master leo_manager[1781]: Root: /usr/local/leofs/current/leo_manager_0
Sep 20 18:56:18 bodies-master epmd[2069]: epmd: failed to listen on socket
```

Nothing in normal log files. It doesn't happen on slave node. Nothing related to managers is happening at both times (no nodes connecting/disconnecting, no bucket-related operations, no leofs-adm commands at all), and the manager was working for few days (since 15th) without restarts before the first crash.
Scientific Linux 7.3, Erlang 20 from erlang-solutions.com:
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
```
(except for epmd which is taken from official packages, for systemd socket support).
This is OpenVZ container so the kernel is
```
[root@bodies-master ~]# uname -a
Linux bodies-master 2.6.32-042stab123.9 #1 SMP Thu Jun 29 13:01:59 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Slave node is running fine on the same kernel on different host. No hardware problems, AFAIK. The process doesn't seem to be hitting any limits.

I've enabled coredumps right now so I can hopefully get more information next time. Things I'm thinking about are (I will try them out after getting one more crash and hopefully getting a coredump):
1. Try with Erlang 19, no hipe - just as the one from official package
2. Try moving master to non-OpenVZ machine
3. .. anything else?

The closest error I was able to find is https://stackoverflow.com/questions/5463503/rabbitmq-install-issue-on-centos-5-5 - but it's about different problem and doesn't apply here.
I understand that strictly this isn't LeoFS problem but coming from Erlang itself (very generic error from here https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/erts/lib_src/pthread/ethr_event.c#L164) and is related to something in system configuration, but the fact that it's happening just on manager master is kind of strange.

I have no idea why it tries to launch instance of epmd right after main process crashes (this does not happen during normal startup/shutdown/restart); the system-wide instance of epmd is already running at all time and nothing happens to it. But it shouldn't be a problem, just kind of strange that it happens only in this situation. Probably not worth worrying, though.

Any advice?

**Comment by mocchira** [comment]
@vstax Thanks for updating this issue. As you described, that's probably not LeoFS problem (probably Erlang runtime hit some bug in CRIU I think), however it would be good for us to know what part of erlang runtime can cause OpenVZ checkpointing to fail to restore **state** (in this case, memory).

At a first glance, there are some cases CRIU still doesn't support to restore the memory according to their doc (Shared objects (mm/fs) support described on https://criu.org/Todo). the corresponding issue is probably this one (https://github.com/xemul/criu/issues/218).

Actually Erlang runtime uses fork and anonymous mmap combo in a few places so there is a possibility the manger master hit the issue. (however not sure at this moment)
I will dig in deeper when I can spare time.
Also let me know if you get some updates around this problem.

**Comment by vstax** [comment]
@mocchira I will do some experiments.

I'm sorry for using wrong wording here: thing is, OpenVZ checkpoints are not exactly CRIU - they are more of an origin of CRIU technology, that is, CRIU is the project made by the same people to make state save/restore available for everyone on general Linux kernel; they moved checkpoint functionality from (very special) OpenVZ kernel to userspace for that. Right now, checkpoints are more feature complete and reliable (https://criu.org/Comparison_to_other_CR_projects) and they restore memory state, among others. CRIU is supposed to replace kernel checkpoints at some point but AFAIK they are still not as complete and tested. I personally find the whole technology to be a bit doubtful, but people say that it works, and according to our SA all other containers survive freeze/restore just fine.

In this case, host server was rebooted and containers were frozen and restored for reboot time (minutes; maybe tens of minutes, not sure). From application perspective, this case should be about the same as suspending (SIGSTOP) and then resuming a few minutes after. Speculating, it could be that this thread-related code in Erlang runtime simply has problem with the fact the process spent some time in frozen state and not save/restore technology itself. Or maybe (looking at the code) FUTEX_WAIT operation returns something unusual when suspended and restored with checkpoints, something that doesn't happen in other circumstances and Erlang code simply never supported that because they never encountered the case.

**Comment by mocchira** [comment]
@vstax Thanks for the explanation in detail.

> In this case, host server was rebooted and containers were frozen and restored for reboot time (minutes; maybe tens of minutes, not sure). From application perspective, this case should be about the same as suspending (SIGSTOP) and then resuming a few minutes after. Speculating, it could be that this thread-related code in Erlang runtime simply has problem with the fact the process spent some time in frozen state and not save/restore technology itself. Or maybe (looking at the code) FUTEX_WAIT operation returns something unusual when suspended and restored with checkpoints, something that doesn't happen in other circumstances and Erlang code simply never supported that because they never encountered the case.

Thanks to your comment above, I've found the culprit here
https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/erts/lib_src/pthread/ethr_event.c#L128-L130
if ETHR_HAVE_ETHR_GET_MONOTONIC_TIME enabled, the code above try to subtract the time taken by the spin lock block here (https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/erts/lib_src/pthread/ethr_event.c#L111-L125) from `timeout`. It usually works as expected however in our case, what if suspending (SIGSTOP) happens during the spin lock block and take minutes? yes `time` could be negative and that cause futex to return EINVAL according to https://lwn.net/Articles/394175/ and you got 
```
Sep 20 18:55:53 bodies-master leo_manager[406]: pthread/ethr_event.c:164: Fatal error in wait__(): Invalid argument (22)
```
That's it.
So I think it's a bug in Erlang itself and have to fix it as glibc developers had to deal with it in the past as mentioned above link (lwn.net).

I will try to send a patch to Erlang when I can spare time.
Thanks!

**Comment by vstax** [comment]
@mocchira Thank you for looking into this in depth!
My test show this kind of crash happens even during very fast suspend & resume from checkpoint (just a few seconds); I have no idea if the fact that EINVAL is returned here is a bug of checkpoints or spec. I tried to get a coredump but it's not working for some reason, I'll try again and will look into the state if I succeed (hope "time" or "tsp" will be there to check if it's negative or it's something else). I will share when I get something (hopefully).

(unfortunately, attaching with gdb beforehand doesn't work because checkpoints refuse to work when there are traced processes, as they can't suspend/resume that)

**Comment by vstax** [comment]
I got coredump (however I had to go back to Erlang 19.3.6.2, as erlang-solutions.com's package doesn't provide debug information and I couldn't find any proper srpm for Erlang 20, instead of trying to make it on my own I just rebuilt Erlang 19 from Fedora). According to dump, none of the threads waiting on that call had negative time / tv_sec. Each and every got EINVAL, though. No idea why. According to source it's supposed to store parameters and restart futex_wait operation on resume: [suspend](https://src.openvz.org/projects/OVZL/repos/linux-2.6.32-openvz/browse/kernel/cpt/cpt_process.c#1030) and [resume](https://src.openvz.org/projects/OVZL/repos/linux-2.6.32-openvz/browse/kernel/cpt/rst_undump.c#438).

Just in case, backtrace of the main thread:
```
#0  0x00007fa88ab121f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 5862
        selftid = 6094
#1  0x00007fa88ab138e8 in __GI_abort () at abort.c:90
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x6404686e6962652f, sa_sigaction = 0x6404686e6962652f}, sa_mask = {__val = {7091324932765845760, 7598528521256788585, 3327649278841794401, 7598528521256788585, 3327649278841794401, 0, 140361858431646, 140358178560784, 4294967297, 0, 140358178560768, 73, 140361858952985, 140361861806576, 73, 140361861806576}}, sa_flags = -1352669440, sa_restorer = 0x47}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000000000659149 in ethr_abort__ () at pthread/ethread.c:768
No locals.
#3  0x0000000000652e30 in ethr_fatal_error__ (file=file@entry=0x698794 "pthread/ethr_event.c", line=line@entry=164, func=func@entry=0x6987b0 <__FUNCTION__.5715> "wait__", err=22) at common/ethr_aux.c:682
        errstr = <optimized out>
#4  0x000000000065962a in wait__ (timeout=340812840174, spincount=0, e=0x7fa845bc0c10) at pthread/ethr_event.c:164
        res = <optimized out>
        time = <optimized out>
        tsp = <optimized out>
        val = <optimized out>
        ts = {tv_sec = 340, tv_nsec = 812840174}
        start = <optimized out>
#5  ethr_event_twait (e=e@entry=0x7fa845bc0c10, timeout=timeout@entry=340812840174) at pthread/ethr_event.c:643
No locals.
#6  0x00000000004ed3bc in erts_tse_twait (tmo=340812840174, ep=0x7fa845bc0c00) at beam/erl_threads.h:3523
        res = <optimized out>
        __erts_msacc_cache = <optimized out>
        __erts_msacc_state = 4
#7  scheduler_wait (fcalls=fcalls@entry=0x7fa7af5fdc90, esdp=esdp@entry=0x7fa844df26c0, rq=rq@entry=0x7fa844d87d40) at beam/erl_process.c:3189
        timeout = 340812840174
        timeout_time = 361274000000
        do_timeout = <optimized out>
        current_time = <optimized out>
        working = <optimized out>
        ssi = 0x7fa844d8a440
        spincount = <optimized out>
        aux_work = 0
        thr_prgr_active = 0
        flgs = <optimized out>
        __erts_msacc_cache = 0x0
        __erts_msacc_state = 4
#8  0x00000000004f81b4 in erts_schedule (esdp=<optimized out>, p=<optimized out>, calls=<optimized out>) at beam/erl_process.c:9813
        psflg_running = <optimized out>
        psflg_running_sys = <optimized out>
        mps = <optimized out>
        mp = <optimized out>
        proxy_p = 0x0
        rq = 0x7fa844d87d40
        context_reds = 2000
        fcalls = 256054
        input_reductions = 4000
        actual_reds = <optimized out>
        reds = <optimized out>
        flags = <optimized out>
        state = 34111530
        is_normal_sched = 1
        __erts_msacc_cache = 0x0
        __erts_msacc_state = <optimized out>
#9  0x000000000043f54d in process_main () at beam/beam_emu.c:1338
        init_done = 1
        c_p = 0x7fa846300400
        reds_used = 16
        reg = 0x7fa84414a280
        opcodes = {0x441686 <process_main+8582>, 0x442171 <process_main+11377>, 0x4420f2 <process_main+11250>, 0x4416d0 <process_main+8656>, 0x441615 <process_main+8469>, 0x445a6a <process_main+25962>, 0x444925 <process_main+21541>, 0x4459fc <process_main+25852>, 0x445ec9 <process_main+27081>, 0x445ad2 <process_main+26066>, 0x4434d6 <process_main+16342>, 0x443264 <process_main+15716>, 0x443f43 <process_main+19011>, 0x441922 <process_main+9250>, 0x443dd4 <process_main+18644>, 0x443f19 <process_main+18969>, 0x445629 <process_main+24873>, 0x44556c <process_main+24684>, 0x44553e <process_main+24638>, 0x445517 <process_main+24599>, 0x445595 <process_main+24725>, 0x4426e6 <process_main+12774>, 0x445947 <process_main+25671>, 0x4449ff <process_main+21759>, 0x445898 <process_main+25496>, 0x44287a <process_main+13178>, 0x442806 <process_main+13062>, 0x4448cc <process_main+21452>, 0x443d28 <process_main+18472>, 0x441602 <process_main+8450>, 0x43fd42 <process_main+2114>, 0x43f820 <process_main+800>, 0x4451b6 <process_main+23734>, 0x445162 <process_main+23650>, 0x4450ef <process_main+23535>, 0x44512e <process_main+23598>, 0x4415df <process_main+8415>, 0x4415bc <process_main+8380>, 0x441591 <process_main+8337>, 0x441567 <process_main+8295>, 0x441545 <process_main+8261>, 0x441519 <process_main+8217>, 0x4414e2 <process_main+8162>, 0x4414ac <process_main+8108>, 0x441476 <process_main+8054>, 0x441441 <process_main+8001>, 0x44140b <process_main+7947>, 0x4413d6 <process_main+7894>, 0x4413a1 <process_main+7841>, 0x44136d <process_main+7789>, 0x444e3c <process_main+22844>, 0x444e9b <process_main+22939>, 0x444e4a <process_main+22858>, 0x444ee9 <process_main+23017>, 0x444cc2 <process_main+22466>, 0x444c34 <process_main+22324>, 0x4425d8 <process_main+12504>, 0x445995 <process_main+25749>, 0x445b4e <process_main+26190>, 0x445af2 <process_main+26098>, 0x44255e <process_main+12382>, 0x4424f3 <process_main+12275>, 0x442f00 <process_main+14848>, 0x444a75 <process_main+21877>, 0x4431c6 <process_main+15558>, 0x4432d7 <process_main+15831>, 0x442b99 <process_main+13977>, 0x443e87 <process_main+18823>, 0x4446be <process_main+20926>, 0x444780 <process_main+21120>, 0x4417f6 <process_main+8950>, 0x444660 <process_main+20832>, 0x444570 <process_main+20592>, 0x441954 <process_main+9300>, 0x443a96 <process_main+17814>, 0x443a08 <process_main+17672>, 0x4455ba <process_main+24762>, 0x4439c6 <process_main+17606>, 0x441a60 <process_main+9568>, 0x44189e <process_main+9118>, 0x4418e2 <process_main+9186>, 0x4440a7 <process_main+19367>, 0x44438a <process_main+20106>, 0x4442c8 <process_main+19912>, 0x444371 <process_main+20081>, 0x4442fb <process_main+19963>, 0x443b31 <process_main+17969>, 0x444202 <process_main+19714>, 0x444246 <process_main+19782>, 0x444293 <process_main+19859>, 0x4441ec <process_main+19692>, 0x444008 <process_main+19208>, 0x444093 <process_main+19347>, 0x44176e <process_main+8814>, 0x443e16 <process_main+18710>, 0x445780 <process_main+25216>, 0x44172e <process_main+8750>, 0x44174e <process_main+8782>, 0x444500 <process_main+20480>, 0x44448d <process_main+20365>, 0x444458 <process_main+20312>, 0x445468 <process_main+24424>, 0x444446 <process_main+20294>, 0x444398 <process_main+20120>, 0x4457ba <process_main+25274>, 0x445809 <process_main+25353>, 0x445723 <process_main+25123>, 0x4456cf <process_main+25039>, 0x44269d <process_main+12701>, 0x442c05 <process_main+14085>, 0x442b29 <process_main+13865>, 0x43f894 <process_main+916>, 0x43f904 <process_main+1028>, 0x43f8c3 <process_main+963>, 0x43f93d <process_main+1085>, 0x445bb9 <process_main+26297>, 0x445667 <process_main+24935>, 0x43f85d <process_main+861>, 0x43f839 <process_main+825>, 0x444d9e <process_main+22686>, 0x4423b6 <process_main+11958>, 0x442408 <process_main+12040>, 0x4447e5 <process_main+21221>, 0x44391c <process_main+17436>, 0x4438c8 <process_main+17352>, 0x43f820 <process_main+800>, 0x444d4d <process_main+22605>, 0x44483a <process_main+21306>, 0x444cfd <process_main+22525>, 0x445228 <process_main+23848>, 0x443c5c <process_main+18268>, 0x44335e <process_main+15966>, 0x442c90 <process_main+142
#10 0x00000000004e342d in sched_thread_func (vesdp=0x7fa844df26c0) at beam/erl_process.c:8206
        callbacks = {arg = 0x7fa844d8a440, wakeup = 0x4e5a90 <thr_prgr_wakeup>, prepare_wait = 0x4e3060 <thr_prgr_prep_wait>, wait = 0x4e3ee0 <thr_prgr_wait>, finalize_wait = 0x4e3040 <thr_prgr_fin_wait>}
        esdp = 0x7fa844df26c0
        no = 11
        tse = 0x7fa845bc0c00
#11 0x0000000000658b0b in thr_wrapper (vtwd=<optimized out>) at pthread/ethread.c:114
        result = 0
        res = <optimized out>
        thr_func = 0x4e3320 <sched_thread_func>
        arg = 0x7fa844df26c0
        tsep = 0x7fa845bc00c0
#12 0x00007fa88b0afe25 in start_thread (arg=0x7fa7af5fe700) at pthread_create.c:308
        __res = <optimized out>
        pd = 0x7fa7af5fe700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140358178563840, 2059852026612811637, 0, 140358178564544, 140358178563840, 400, -2028504126570100875, -2033649470587402379}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
#13 0x00007fa88abd534d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```
Backtrace for all threads is attached at [beam-smp-bt.txt.gz](https://github.com/leo-project/leofs/files/1334666/beam-smp-bt.txt.gz)

I think it's probably best to drop the whole issue, it's likely just not worth spending more time on it.

**Comment by mocchira** [comment]
@vstax Thanks for further digging.

> I think it's probably best to drop the whole issue, it's likely just not worth spending more time on it.

Agreed.
Please drop if you don't have any problem.
(I will keep digging in my spare time out of curiosity and comment here if I find something interesting)
